-- The LDBC Social Network Benchmark data as relational tables (decision 110): tables and
-- primary keys only. Foreign keys are in constraints.sql and indexes in indexes.sql, which run after the
-- data is loaded, so that a bulk load is not checked row by row.
--
-- Data generated by the LDBC SNB Datagen, used under CC-BY 4.0. This is not an LDBC
-- Benchmark and nothing measured over this schema is an LDBC Benchmark result.
--
-- The relational mapping follows the reference implementations of LDBC itself rather than
-- inventing one, and deviates from the serialized files in the same places they do:
--   * Post and Comment are one table, Message, as in the PostgreSQL implementation of
--     Interactive v1 and the Umbra implementation of BI. A comment is a message with a
--     ParentMessageId; a post has none.
--   * Every message carries the root post of its thread, the forum that contains that post
--     and its language (RootPostId, ContainerForumId, RootPostLanguage), as the Message table
--     of the BI implementation does. Walking replyOf to the root is otherwise recursion.
--   * Person_knows_Person holds every friendship in both directions: the files serialize an
--     undirected edge once and leave it to the loader.
--   * Place and Organisation stay single tables with a Type discriminator, as the files have
--     them; City, Country, Continent, University and Company are values of Type.
-- Every string column compares binary, because the specification orders strings by code
-- point (section 4.1) and a case-insensitive collation would break its ties differently.
-- A column the data fills with more than ASCII - names, titles, content, and the DBpedia
-- URLs, which carry the names - is NVARCHAR; codes, addresses and file names are VARCHAR.
--
-- The {{schema}} placeholder is dbo in the LdbcSnb database of the container and a schema of
-- its own in the test database, where the suite uses these tables as the catalog of the
-- LDBC query catalog. Batches are separated by a line containing only GO.

-- Static part: the same at every scale factor.

CREATE TABLE [{{schema}}].[Place] (
    [Id]             BIGINT         NOT NULL,
    [Name]           NVARCHAR(256)  COLLATE Latin1_General_100_BIN2 NOT NULL,
    [Url]            NVARCHAR(256)  COLLATE Latin1_General_100_BIN2 NOT NULL,
    [Type]           VARCHAR(12)    COLLATE Latin1_General_100_BIN2 NOT NULL,
    [PartOfPlaceId]  BIGINT         NULL,
    CONSTRAINT [PK_Place] PRIMARY KEY ([Id])
);
GO

CREATE TABLE [{{schema}}].[Organisation] (
    [Id]               BIGINT         NOT NULL,
    [Type]             VARCHAR(12)    COLLATE Latin1_General_100_BIN2 NOT NULL,
    [Name]             NVARCHAR(256)  COLLATE Latin1_General_100_BIN2 NOT NULL,
    [Url]              NVARCHAR(256)  COLLATE Latin1_General_100_BIN2 NOT NULL,
    [LocationPlaceId]  BIGINT         NOT NULL,
    CONSTRAINT [PK_Organisation] PRIMARY KEY ([Id])
);
GO

CREATE TABLE [{{schema}}].[TagClass] (
    [Id]                    BIGINT         NOT NULL,
    [Name]                  NVARCHAR(256)  COLLATE Latin1_General_100_BIN2 NOT NULL,
    [Url]                   NVARCHAR(256)  COLLATE Latin1_General_100_BIN2 NOT NULL,
    [SubclassOfTagClassId]  BIGINT         NULL,
    CONSTRAINT [PK_TagClass] PRIMARY KEY ([Id])
);
GO

CREATE TABLE [{{schema}}].[Tag] (
    [Id]              BIGINT         NOT NULL,
    [Name]            NVARCHAR(256)  COLLATE Latin1_General_100_BIN2 NOT NULL,
    [Url]             NVARCHAR(256)  COLLATE Latin1_General_100_BIN2 NOT NULL,
    [TypeTagClassId]  BIGINT         NOT NULL,
    CONSTRAINT [PK_Tag] PRIMARY KEY ([Id])
);
GO

-- Dynamic part: people, forums, messages and the edges between them.

CREATE TABLE [{{schema}}].[Person] (
    [Id]              BIGINT         NOT NULL,
    [FirstName]       NVARCHAR(80)   COLLATE Latin1_General_100_BIN2 NOT NULL,
    [LastName]        NVARCHAR(80)   COLLATE Latin1_General_100_BIN2 NOT NULL,
    [Gender]          VARCHAR(10)    COLLATE Latin1_General_100_BIN2 NOT NULL,
    [Birthday]        DATE           NOT NULL,
    [CreationDate]    DATETIME2(3)   NOT NULL,
    [LocationIp]      VARCHAR(40)    COLLATE Latin1_General_100_BIN2 NOT NULL,
    [BrowserUsed]     VARCHAR(40)    COLLATE Latin1_General_100_BIN2 NOT NULL,
    [LocationCityId]  BIGINT         NOT NULL,
    CONSTRAINT [PK_Person] PRIMARY KEY ([Id])
);
GO

CREATE TABLE [{{schema}}].[Person_email_EmailAddress] (
    [PersonId]  BIGINT        NOT NULL,
    [Email]     VARCHAR(256)  COLLATE Latin1_General_100_BIN2 NOT NULL,
    CONSTRAINT [PK_Person_email_EmailAddress] PRIMARY KEY ([PersonId], [Email])
);
GO

CREATE TABLE [{{schema}}].[Person_speaks_Language] (
    [PersonId]  BIGINT       NOT NULL,
    [Language]  VARCHAR(40)  COLLATE Latin1_General_100_BIN2 NOT NULL,
    CONSTRAINT [PK_Person_speaks_Language] PRIMARY KEY ([PersonId], [Language])
);
GO

CREATE TABLE [{{schema}}].[Forum] (
    [Id]                 BIGINT         NOT NULL,
    [Title]              NVARCHAR(256)  COLLATE Latin1_General_100_BIN2 NOT NULL,
    [CreationDate]       DATETIME2(3)   NOT NULL,
    [ModeratorPersonId]  BIGINT         NULL,
    CONSTRAINT [PK_Forum] PRIMARY KEY ([Id])
);
GO

-- A post has ImageFile or Content, never both, and no ParentMessageId; a comment has
-- Content and a ParentMessageId. RootPostId of a post is its own Id.
CREATE TABLE [{{schema}}].[Message] (
    [Id]                 BIGINT          NOT NULL,
    [CreationDate]       DATETIME2(3)    NOT NULL,
    [LocationIp]         VARCHAR(40)     COLLATE Latin1_General_100_BIN2 NOT NULL,
    [BrowserUsed]        VARCHAR(40)     COLLATE Latin1_General_100_BIN2 NOT NULL,
    [Content]            NVARCHAR(2000)  COLLATE Latin1_General_100_BIN2 NULL,
    [ImageFile]          VARCHAR(256)    COLLATE Latin1_General_100_BIN2 NULL,
    [Length]             INT             NOT NULL,
    [CreatorPersonId]    BIGINT          NOT NULL,
    [LocationCountryId]  BIGINT          NOT NULL,
    [ParentMessageId]    BIGINT          NULL,
    [RootPostId]         BIGINT          NOT NULL,
    [ContainerForumId]   BIGINT          NOT NULL,
    [RootPostLanguage]   VARCHAR(40)     COLLATE Latin1_General_100_BIN2 NULL,
    CONSTRAINT [PK_Message] PRIMARY KEY ([Id])
);
GO

CREATE TABLE [{{schema}}].[Person_knows_Person] (
    [Person1Id]     BIGINT        NOT NULL,
    [Person2Id]     BIGINT        NOT NULL,
    [CreationDate]  DATETIME2(3)  NOT NULL,
    CONSTRAINT [PK_Person_knows_Person] PRIMARY KEY ([Person1Id], [Person2Id])
);
GO

CREATE TABLE [{{schema}}].[Person_likes_Message] (
    [PersonId]      BIGINT        NOT NULL,
    [MessageId]     BIGINT        NOT NULL,
    [CreationDate]  DATETIME2(3)  NOT NULL,
    CONSTRAINT [PK_Person_likes_Message] PRIMARY KEY ([PersonId], [MessageId])
);
GO

CREATE TABLE [{{schema}}].[Message_hasTag_Tag] (
    [MessageId]  BIGINT  NOT NULL,
    [TagId]      BIGINT  NOT NULL,
    CONSTRAINT [PK_Message_hasTag_Tag] PRIMARY KEY ([MessageId], [TagId])
);
GO

CREATE TABLE [{{schema}}].[Forum_hasMember_Person] (
    [ForumId]   BIGINT        NOT NULL,
    [PersonId]  BIGINT        NOT NULL,
    [JoinDate]  DATETIME2(3)  NOT NULL,
    CONSTRAINT [PK_Forum_hasMember_Person] PRIMARY KEY ([ForumId], [PersonId])
);
GO

CREATE TABLE [{{schema}}].[Forum_hasTag_Tag] (
    [ForumId]  BIGINT  NOT NULL,
    [TagId]    BIGINT  NOT NULL,
    CONSTRAINT [PK_Forum_hasTag_Tag] PRIMARY KEY ([ForumId], [TagId])
);
GO

CREATE TABLE [{{schema}}].[Person_hasInterest_Tag] (
    [PersonId]  BIGINT  NOT NULL,
    [TagId]     BIGINT  NOT NULL,
    CONSTRAINT [PK_Person_hasInterest_Tag] PRIMARY KEY ([PersonId], [TagId])
);
GO

CREATE TABLE [{{schema}}].[Person_studyAt_University] (
    [PersonId]      BIGINT  NOT NULL,
    [UniversityId]  BIGINT  NOT NULL,
    [ClassYear]     INT     NOT NULL,
    CONSTRAINT [PK_Person_studyAt_University] PRIMARY KEY ([PersonId], [UniversityId])
);
GO

CREATE TABLE [{{schema}}].[Person_workAt_Company] (
    [PersonId]   BIGINT  NOT NULL,
    [CompanyId]  BIGINT  NOT NULL,
    [WorkFrom]   INT     NOT NULL,
    CONSTRAINT [PK_Person_workAt_Company] PRIMARY KEY ([PersonId], [CompanyId])
);
GO
