using AdvisorBenchmarking;
using OrmConvertor;
using ORMConvertorAPI.Services;

namespace ORMConvertorAPI;

public class Program
{
    public static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);

        // Add services to the container. No authentication scheme and no authorization
        // policy are registered: every endpoint is open, which is what the deployment
        // assumes (a trusted network or a proxy in front) and what docs/threat-model.md
        // records. The template's authorization services used to sit here and guarded
        // nothing, which read as protection where there was none.
        builder.Services.AddSingleton<IBenchmarkExecutor, BenchmarkExecutor>();
        builder.Services.AddSingleton<IAdvisorRunCoordinator, AdvisorRunCoordinator>();

        // The OpenAPI document is generated by Microsoft.AspNetCore.OpenApi and served in
        // every environment, because the REST contract is one of the three surfaces the
        // version number protects (decision 041) and a contract nobody can read in
        // Production is not much of a contract. Swashbuckle is kept for the UI only - one
        // document, one generator, so the two cannot describe different APIs.
        builder.Services.AddEndpointsApiExplorer();
        builder.Services.AddOpenApi(options =>
            // Without this the document would state a version of its own, which is exactly
            // the second place decision 034 exists to prevent. The number comes from the
            // assembly, so the contract cannot claim a version the build did not produce.
            options.AddDocumentTransformer((document, _, _) =>
            {
                document.Info.Title = "ORMConvertor";
                document.Info.Version = ToolRelease.Version;
                return Task.CompletedTask;
            }));

        var app = builder.Build();

        app.UsePathBase("/orm");
        // Before UseRouting: static assets are endpoints, so the rewrite of "/" to
        // index.html has to happen before endpoint matching, not after it.
        app.UseDefaultFiles();
        app.UseRouting();

        // Configure the HTTP request pipeline.
        // The document itself is unconditional; only the UI on top of it is a development
        // convenience. Both live under the "/orm" path base, so the UI is pointed at a
        // path relative to itself rather than at "/openapi/v1.json", which would miss the
        // prefix behind a proxy that requires it.
        app.MapOpenApi();
        if (app.Environment.IsDevelopment())
        {
            app.UseSwaggerUI(options =>
                options.SwaggerEndpoint("../openapi/v1.json", "ORMConvertor"));
        }

        Endpoints.Map(app);

        // Serves the .br/.gz copies the publish already produces, chosen by the
        // request's Accept-Encoding; UseStaticFiles never looked at them.
        app.MapStaticAssets();

        app.Run();
    }
}
