<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="frontend\**" />
    <EmbeddedResource Remove="frontend\**" />
    <None Remove="frontend\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AbstractWrappers\AbstractWrappers.csproj" />
    <ProjectReference Include="..\CSharpEntityParsing\CSharpEntityParsing.csproj" />
    <ProjectReference Include="..\LinqParsing\LinqParsing.csproj" />
  </ItemGroup>

</Project>
