namespace SampleData;

/// <summary>
/// The LDBC Social Network Benchmark as input to the tool (decision 110): Dapper entity
/// classes over the tables of <c>database/ldbc/schema.sql</c>, and the 41 read queries of the
/// Interactive and Business Intelligence workloads of the specification (version 2.2.4), each
/// written as T-SQL over those tables or marked as one the tool does not translate.
///
/// Dapper is the source because the reference implementations of LDBC are SQL, so a query
/// here can be set beside theirs, and because a Dapper source states no key or relation of
/// its own: every such fact comes from the catalog, and with LdbcSnb as the catalog it comes
/// from the very tables the data set was loaded into.
///
/// Data generated by the LDBC SNB Datagen, used under CC-BY 4.0. This is not an LDBC
/// Benchmark, and nothing run over these queries is an LDBC Benchmark result.
///
/// The queries repeat four subqueries: the friends of the start person (one step along
/// knows) and the persons two, three and four steps away. They are walks, not distances -
/// a friend is also two steps away, over the start person and back - and the queries say
/// "within n steps" as the union of the walks of length 1 to n, and "exactly n" by excluding
/// the shorter ones. That is how a path of bounded length is stated without recursion.
/// </summary>
public static class LdbcSnbSample
{
    /// <summary>The Dapper entity classes, one file per table, in the order of schema.sql.</summary>
    public static IReadOnlyList<(string FileName, string Content)> Entities { get; } =
    [
        ("Place.cs", """
            namespace LdbcSnb;

            public class Place
            {
                public long Id { get; set; }

                public string Name { get; set; } = "";

                public string Url { get; set; } = "";

                public string Type { get; set; } = "";

                public long? PartOfPlaceId { get; set; }
            }

            """),
        ("Organisation.cs", """
            namespace LdbcSnb;

            public class Organisation
            {
                public long Id { get; set; }

                public string Type { get; set; } = "";

                public string Name { get; set; } = "";

                public string Url { get; set; } = "";

                public long LocationPlaceId { get; set; }
            }

            """),
        ("TagClass.cs", """
            namespace LdbcSnb;

            public class TagClass
            {
                public long Id { get; set; }

                public string Name { get; set; } = "";

                public string Url { get; set; } = "";

                public long? SubclassOfTagClassId { get; set; }
            }

            """),
        ("Tag.cs", """
            namespace LdbcSnb;

            public class Tag
            {
                public long Id { get; set; }

                public string Name { get; set; } = "";

                public string Url { get; set; } = "";

                public long TypeTagClassId { get; set; }
            }

            """),
        ("Person.cs", """
            namespace LdbcSnb;

            public class Person
            {
                public long Id { get; set; }

                public string FirstName { get; set; } = "";

                public string LastName { get; set; } = "";

                public string Gender { get; set; } = "";

                public DateOnly Birthday { get; set; }

                public DateTime CreationDate { get; set; }

                public string LocationIp { get; set; } = "";

                public string BrowserUsed { get; set; } = "";

                public long LocationCityId { get; set; }
            }

            """),
        ("Person_email_EmailAddress.cs", """
            namespace LdbcSnb;

            public class Person_email_EmailAddress
            {
                public long PersonId { get; set; }

                public string Email { get; set; } = "";
            }

            """),
        ("Person_speaks_Language.cs", """
            namespace LdbcSnb;

            public class Person_speaks_Language
            {
                public long PersonId { get; set; }

                public string Language { get; set; } = "";
            }

            """),
        ("Forum.cs", """
            namespace LdbcSnb;

            public class Forum
            {
                public long Id { get; set; }

                public string Title { get; set; } = "";

                public DateTime CreationDate { get; set; }

                public long? ModeratorPersonId { get; set; }
            }

            """),
        ("Message.cs", """
            namespace LdbcSnb;

            public class Message
            {
                public long Id { get; set; }

                public DateTime CreationDate { get; set; }

                public string LocationIp { get; set; } = "";

                public string BrowserUsed { get; set; } = "";

                public string? Content { get; set; }

                public string? ImageFile { get; set; }

                public int Length { get; set; }

                public long CreatorPersonId { get; set; }

                public long LocationCountryId { get; set; }

                public long? ParentMessageId { get; set; }

                public long RootPostId { get; set; }

                public long ContainerForumId { get; set; }

                public string? RootPostLanguage { get; set; }
            }

            """),
        ("Person_knows_Person.cs", """
            namespace LdbcSnb;

            public class Person_knows_Person
            {
                public long Person1Id { get; set; }

                public long Person2Id { get; set; }

                public DateTime CreationDate { get; set; }
            }

            """),
        ("Person_likes_Message.cs", """
            namespace LdbcSnb;

            public class Person_likes_Message
            {
                public long PersonId { get; set; }

                public long MessageId { get; set; }

                public DateTime CreationDate { get; set; }
            }

            """),
        ("Message_hasTag_Tag.cs", """
            namespace LdbcSnb;

            public class Message_hasTag_Tag
            {
                public long MessageId { get; set; }

                public long TagId { get; set; }
            }

            """),
        ("Forum_hasMember_Person.cs", """
            namespace LdbcSnb;

            public class Forum_hasMember_Person
            {
                public long ForumId { get; set; }

                public long PersonId { get; set; }

                public DateTime JoinDate { get; set; }
            }

            """),
        ("Forum_hasTag_Tag.cs", """
            namespace LdbcSnb;

            public class Forum_hasTag_Tag
            {
                public long ForumId { get; set; }

                public long TagId { get; set; }
            }

            """),
        ("Person_hasInterest_Tag.cs", """
            namespace LdbcSnb;

            public class Person_hasInterest_Tag
            {
                public long PersonId { get; set; }

                public long TagId { get; set; }
            }

            """),
        ("Person_studyAt_University.cs", """
            namespace LdbcSnb;

            public class Person_studyAt_University
            {
                public long PersonId { get; set; }

                public long UniversityId { get; set; }

                public int ClassYear { get; set; }
            }

            """),
        ("Person_workAt_Company.cs", """
            namespace LdbcSnb;

            public class Person_workAt_Company
            {
                public long PersonId { get; set; }

                public long CompanyId { get; set; }

                public int WorkFrom { get; set; }
            }

            """),
    ];

    /// <summary>
    /// The EF Core builder renders a join as pairs of equal columns, the one form a LINQ join
    /// takes, and refuses one whose ON clause says more (decision 053). Where the extra
    /// condition belongs to an inner join, the texts put it into WHERE, which means the same;
    /// an outer join keeps its rows by it, so there it stays and EF Core refuses.
    /// </summary>
    private static readonly LdbcRefusal EFCoreJoin = new(Model.ORMEnum.EFCore,
        "A LINQ join matches pairs of equal columns and nothing else, and this query joins on other conditions too - "
        + "filters that an outer join cannot move to WHERE without changing its rows.");

    /// <summary>
    /// A count over the whole result, which LINQ says only by ending the chain in the call,
    /// and no other chain returns the same rows - so EF Core writes it in native SQL
    /// (decision 113).
    /// </summary>
    private static readonly LdbcFallback EFCoreCount = new(Model.ORMEnum.EFCore,
        "A count over the whole result is a call that ends a LINQ chain, not a query, so the query goes out as native SQL through SqlQuery.");

    /// <summary>
    /// A query over the result of another query - a common table expression, a derived table -
    /// has no form in two of the six query languages (decision 112), and those two targets
    /// write it in native SQL (decision 113).
    /// </summary>
    private static readonly LdbcFallback NHibernateIntermediate = new(Model.ORMEnum.NHibernate,
        "HQL of NHibernate 5.7 has neither WITH nor a subquery in FROM, so the query goes out as native SQL through CreateSQLQuery.");

    private static readonly LdbcFallback EclipseLinkIntermediate = new(Model.ORMEnum.EclipseLink,
        "JPQL has neither WITH nor a subquery in FROM - EclipseLink's own subquery in FROM stands only as a cross join beside an entity -, so the query goes out as native SQL through createNativeQuery.");

    /// <summary>
    /// The one shape the native query of EclipseLink cannot take: a list parameter, which it
    /// hands the driver as one value instead of expanding it (decision 113, measured).
    /// </summary>
    private static readonly LdbcRefusal EclipseLinkNativeList = new(Model.ORMEnum.EclipseLink,
        "The query needs native SQL here, and a native query of EclipseLink 5.0 does not expand a list parameter into the values IN ranges over.");

    private static readonly LdbcParameter PersonId = new("personId", "BIGINT", "4398046513938");
    private static readonly LdbcParameter MessageId = new("messageId", "BIGINT", "1374390048303");

    /// <summary>The 41 read queries, in the order of the specification.</summary>
    public static IReadOnlyList<LdbcQuery> Queries { get; } =
    [
        // Interactive short reads (specification section 6.2).

        new("is1", LdbcWorkload.InteractiveShort, 1, "Profile of a person", LdbcTranslation.AsSpecified,
            "A lookup by key. The city is a column of the person, so no join is needed.",
            """
            SELECT p.FirstName, p.LastName, p.Birthday, p.LocationIp, p.BrowserUsed,
                   p.LocationCityId AS CityId, p.Gender, p.CreationDate
            FROM Person AS p
            WHERE p.Id = @personId
            """,
            [PersonId]),

        new("is2", LdbcWorkload.InteractiveShort, 2, "Recent messages of a person", LdbcTranslation.AsSpecified,
            "The last ten messages with the post that started each thread and its author. Walking replyOf up to the root "
            + "post would be recursion; the root post is a column of every message (RootPostId), filled when the data "
            + "is loaded, as in the Message table of the reference implementation of BI.",
            """
            SELECT TOP (10) m.Id AS MessageId, COALESCE(m.Content, m.ImageFile) AS MessageContent,
                   m.CreationDate AS MessageCreationDate, r.Id AS OriginalPostId,
                   a.Id AS OriginalPostAuthorId, a.FirstName AS OriginalPostAuthorFirstName,
                   a.LastName AS OriginalPostAuthorLastName
            FROM Message AS m
            JOIN Message AS r ON r.Id = m.RootPostId
            JOIN Person AS a ON a.Id = r.CreatorPersonId
            WHERE m.CreatorPersonId = @personId
            ORDER BY m.CreationDate DESC, m.Id DESC
            """,
            [PersonId]),

        new("is3", LdbcWorkload.InteractiveShort, 3, "Friends of a person", LdbcTranslation.AsSpecified,
            "One step along knows, ordered by an attribute of the edge itself.",
            """
            SELECT f.Id AS PersonId, f.FirstName, f.LastName, k.CreationDate AS FriendshipCreationDate
            FROM Person_knows_Person AS k
            JOIN Person AS f ON f.Id = k.Person2Id
            WHERE k.Person1Id = @personId
            ORDER BY k.CreationDate DESC, f.Id ASC
            """,
            [PersonId]),

        new("is4", LdbcWorkload.InteractiveShort, 4, "Content of a message", LdbcTranslation.AsSpecified,
            "A lookup by key. A post carries either content or an image file, so the text is the first of the two that is set.",
            """
            SELECT m.CreationDate AS MessageCreationDate, COALESCE(m.Content, m.ImageFile) AS MessageContent
            FROM Message AS m
            WHERE m.Id = @messageId
            """,
            [MessageId]),

        new("is5", LdbcWorkload.InteractiveShort, 5, "Creator of a message", LdbcTranslation.AsSpecified,
            "A lookup by key and one join along a foreign key.",
            """
            SELECT p.Id AS PersonId, p.FirstName, p.LastName
            FROM Message AS m
            JOIN Person AS p ON p.Id = m.CreatorPersonId
            WHERE m.Id = @messageId
            """,
            [MessageId]),

        new("is6", LdbcWorkload.InteractiveShort, 6, "Forum of a message", LdbcTranslation.AsSpecified,
            "The forum that contains the thread of a message and its moderator. A comment reaches its forum through the "
            + "root post of its thread; ContainerForumId carries that forum on every message, filled when the data is loaded.",
            """
            SELECT f.Id AS ForumId, f.Title AS ForumTitle, mo.Id AS ModeratorId,
                   mo.FirstName AS ModeratorFirstName, mo.LastName AS ModeratorLastName
            FROM Message AS m
            JOIN Forum AS f ON f.Id = m.ContainerForumId
            JOIN Person AS mo ON mo.Id = f.ModeratorPersonId
            WHERE m.Id = @messageId
            """,
            [MessageId]),

        new("is7", LdbcWorkload.InteractiveShort, 7, "Replies of a message", LdbcTranslation.AsSpecified,
            "Direct replies with their authors and whether the author of the reply knows the author of the message: an "
            + "outer join along knows and a CASE over whether it found a row. The flag is 1 or 0.",
            """
            SELECT c.Id AS CommentId, c.Content AS CommentContent, c.CreationDate AS CommentCreationDate,
                   ra.Id AS ReplyAuthorId, ra.FirstName AS ReplyAuthorFirstName, ra.LastName AS ReplyAuthorLastName,
                   CASE WHEN k.Person1Id IS NULL THEN 0 ELSE 1 END AS ReplyAuthorKnowsOriginalMessageAuthor
            FROM Message AS m
            JOIN Message AS c ON c.ParentMessageId = m.Id
            JOIN Person AS ra ON ra.Id = c.CreatorPersonId
            LEFT JOIN Person_knows_Person AS k ON k.Person1Id = m.CreatorPersonId AND k.Person2Id = c.CreatorPersonId
            WHERE m.Id = @messageId
            ORDER BY c.CreationDate DESC, ra.Id ASC
            """,
            [MessageId]),

        // Interactive complex reads (specification section 6.1).

        new("ic1", LdbcWorkload.InteractiveComplex, 1, "Transitive friends with a certain name", LdbcTranslation.Simplified,
            "Persons with a given first name within three steps, with the distance as a CASE over the walks of length one "
            + "and two. Left out: the e-mails, languages, universities and companies of each person, which the "
            + "specification returns as lists - one row per person has no place for them.",
            """
            SELECT TOP (20) p.Id AS FriendId, p.LastName AS FriendLastName,
                   CASE
                       WHEN p.Id IN (SELECT k1.Person2Id FROM Person_knows_Person AS k1 WHERE k1.Person1Id = @personId) THEN 1
                       WHEN p.Id IN (SELECT k2.Person2Id FROM Person_knows_Person AS k1
                                     JOIN Person_knows_Person AS k2 ON k2.Person1Id = k1.Person2Id
                                     WHERE k1.Person1Id = @personId) THEN 2
                       ELSE 3
                   END AS DistanceFromPerson,
                   p.Birthday AS FriendBirthday, p.CreationDate AS FriendCreationDate, p.Gender AS FriendGender,
                   p.BrowserUsed AS FriendBrowserUsed, p.LocationIp AS FriendLocationIp, c.Name AS FriendCityName
            FROM Person AS p
            JOIN Place AS c ON c.Id = p.LocationCityId
            WHERE p.FirstName = @firstName
              AND p.Id <> @personId
              AND (p.Id IN (SELECT k1.Person2Id FROM Person_knows_Person AS k1 WHERE k1.Person1Id = @personId)
                   OR p.Id IN (SELECT k2.Person2Id FROM Person_knows_Person AS k1
                               JOIN Person_knows_Person AS k2 ON k2.Person1Id = k1.Person2Id
                               WHERE k1.Person1Id = @personId)
                   OR p.Id IN (SELECT k3.Person2Id FROM Person_knows_Person AS k1
                               JOIN Person_knows_Person AS k2 ON k2.Person1Id = k1.Person2Id
                               JOIN Person_knows_Person AS k3 ON k3.Person1Id = k2.Person2Id
                               WHERE k1.Person1Id = @personId))
            ORDER BY DistanceFromPerson ASC, p.LastName ASC, p.Id ASC
            """,
            [PersonId, new("firstName", "NVARCHAR(80)", "John")]),

        new("ic2", LdbcWorkload.InteractiveComplex, 2, "Recent messages by your friends", LdbcTranslation.AsSpecified,
            "One step along knows, then the messages of the friends before a date, newest first.",
            """
            SELECT TOP (20) f.Id AS PersonId, f.FirstName AS PersonFirstName, f.LastName AS PersonLastName,
                   m.Id AS MessageId, COALESCE(m.Content, m.ImageFile) AS MessageContent,
                   m.CreationDate AS MessageCreationDate
            FROM Person_knows_Person AS k
            JOIN Person AS f ON f.Id = k.Person2Id
            JOIN Message AS m ON m.CreatorPersonId = f.Id
            WHERE k.Person1Id = @personId AND m.CreationDate < @maxDate
            ORDER BY m.CreationDate DESC, m.Id ASC
            """,
            [PersonId, new("maxDate", "DATE", "2012-01-01")]),

        new("ic3", LdbcWorkload.InteractiveComplex, 3, "Friends and friends of friends that have been to given countries", LdbcTranslation.AsSpecified,
            "Friends and friends of friends living outside two countries who wrote messages in both: two counts over "
            + "a CASE, both required by HAVING. The caller passes the end of the window, $startDate + $durationDays, as @endDate.",
            """
            SELECT TOP (20) p.Id AS OtherPersonId, p.FirstName AS OtherPersonFirstName, p.LastName AS OtherPersonLastName,
                   COUNT(DISTINCT CASE WHEN mc.Name = @countryXName THEN m.Id END) AS XCount,
                   COUNT(DISTINCT CASE WHEN mc.Name = @countryYName THEN m.Id END) AS YCount,
                   COUNT(DISTINCT m.Id) AS MessageCount
            FROM Person AS p
            JOIN Place AS ci ON ci.Id = p.LocationCityId
            JOIN Place AS co ON co.Id = ci.PartOfPlaceId
            JOIN Message AS m ON m.CreatorPersonId = p.Id
            JOIN Place AS mc ON mc.Id = m.LocationCountryId
            WHERE p.Id <> @personId
              AND (p.Id IN (SELECT k1.Person2Id FROM Person_knows_Person AS k1 WHERE k1.Person1Id = @personId)
                   OR p.Id IN (SELECT k2.Person2Id FROM Person_knows_Person AS k1
                               JOIN Person_knows_Person AS k2 ON k2.Person1Id = k1.Person2Id
                               WHERE k1.Person1Id = @personId))
              AND co.Name <> @countryXName AND co.Name <> @countryYName
              AND (mc.Name = @countryXName OR mc.Name = @countryYName)
              AND m.CreationDate >= @startDate AND m.CreationDate < @endDate
            GROUP BY p.Id, p.FirstName, p.LastName
            HAVING COUNT(DISTINCT CASE WHEN mc.Name = @countryXName THEN m.Id END) > 0
               AND COUNT(DISTINCT CASE WHEN mc.Name = @countryYName THEN m.Id END) > 0
            ORDER BY MessageCount DESC, p.Id ASC
            """,
            [PersonId, new("countryXName", "NVARCHAR(256)", "India"), new("countryYName", "NVARCHAR(256)", "China"),
             new("startDate", "DATE", "2011-01-01"), new("endDate", "DATE", "2011-07-01")]),

        new("ic4", LdbcWorkload.InteractiveComplex, 4, "New topics", LdbcTranslation.AsSpecified,
            "Tags on the friends' posts inside a window that no friend's post carried before it: a correlated NOT EXISTS "
            + "and a grouped count. The caller passes $startDate + $durationDays as @endDate.",
            """
            SELECT TOP (10) t.Name AS TagName, COUNT(DISTINCT m.Id) AS PostCount
            FROM Person_knows_Person AS k
            JOIN Message AS m ON m.CreatorPersonId = k.Person2Id
            JOIN Message_hasTag_Tag AS mt ON mt.MessageId = m.Id
            JOIN Tag AS t ON t.Id = mt.TagId
            WHERE k.Person1Id = @personId
              AND m.ParentMessageId IS NULL
              AND m.CreationDate >= @startDate AND m.CreationDate < @endDate
              AND NOT EXISTS (
                  SELECT o.Id
                  FROM Person_knows_Person AS k2
                  JOIN Message AS o ON o.CreatorPersonId = k2.Person2Id
                  JOIN Message_hasTag_Tag AS ot ON ot.MessageId = o.Id
                  WHERE k2.Person1Id = @personId
                    AND o.ParentMessageId IS NULL
                    AND o.CreationDate < @startDate
                    AND ot.TagId = t.Id)
            GROUP BY t.Name
            ORDER BY PostCount DESC, t.Name ASC
            """,
            [PersonId, new("startDate", "DATE", "2011-06-01"), new("endDate", "DATE", "2011-07-01")]),

        new("ic5", LdbcWorkload.InteractiveComplex, 5, "New groups", LdbcTranslation.AsSpecified,
            "Forums that friends and friends of friends joined after a date, with the posts they wrote there; an outer "
            + "join keeps the forums where they wrote none.",
            """
            SELECT TOP (20) f.Title AS ForumTitle, COUNT(DISTINCT m.Id) AS PostCount
            FROM Forum_hasMember_Person AS fm
            JOIN Forum AS f ON f.Id = fm.ForumId
            LEFT JOIN Message AS m ON m.ContainerForumId = f.Id AND m.CreatorPersonId = fm.PersonId AND m.ParentMessageId IS NULL
            WHERE fm.JoinDate > @minDate
              AND fm.PersonId <> @personId
              AND (fm.PersonId IN (SELECT k1.Person2Id FROM Person_knows_Person AS k1 WHERE k1.Person1Id = @personId)
                   OR fm.PersonId IN (SELECT k2.Person2Id FROM Person_knows_Person AS k1
                                      JOIN Person_knows_Person AS k2 ON k2.Person1Id = k1.Person2Id
                                      WHERE k1.Person1Id = @personId))
            GROUP BY f.Id, f.Title
            ORDER BY PostCount DESC, f.Id ASC
            """,
            [PersonId, new("minDate", "DATE", "2012-06-01")], [EFCoreJoin]),

        new("ic6", LdbcWorkload.InteractiveComplex, 6, "Tag co-occurrence", LdbcTranslation.AsSpecified,
            "The tags that appear beside a given tag on posts of friends and friends of friends: two joins over the same "
            + "edge table and a grouped count.",
            """
            SELECT TOP (10) ot.Name AS OtherTagName, COUNT(DISTINCT m.Id) AS PostCount
            FROM Message AS m
            JOIN Message_hasTag_Tag AS mt ON mt.MessageId = m.Id
            JOIN Tag AS t ON t.Id = mt.TagId
            JOIN Message_hasTag_Tag AS mo ON mo.MessageId = m.Id
            JOIN Tag AS ot ON ot.Id = mo.TagId
            WHERE t.Name = @tagName
              AND ot.Id <> t.Id
              AND m.ParentMessageId IS NULL
              AND m.CreatorPersonId <> @personId
              AND (m.CreatorPersonId IN (SELECT k1.Person2Id FROM Person_knows_Person AS k1 WHERE k1.Person1Id = @personId)
                   OR m.CreatorPersonId IN (SELECT k2.Person2Id FROM Person_knows_Person AS k1
                                            JOIN Person_knows_Person AS k2 ON k2.Person1Id = k1.Person2Id
                                            WHERE k1.Person1Id = @personId))
            GROUP BY ot.Name
            ORDER BY PostCount DESC, ot.Name ASC
            """,
            [PersonId, new("tagName", "NVARCHAR(256)", "Augustine_of_Hippo")]),

        new("ic7", LdbcWorkload.InteractiveComplex, 7, "Recent likers", LdbcTranslation.Simplified,
            "The most recent like of every person who liked the start person's messages - an arg-max per person, written "
            + "as a NOT EXISTS of a later like - and whether the liker is a friend. Left out: the latency in minutes "
            + "between the message and the like, which is date arithmetic the representation does not carry; the text "
            + "returns the creation date of the message instead.",
            """
            SELECT TOP (20) f.Id AS PersonId, f.FirstName AS PersonFirstName, f.LastName AS PersonLastName,
                   l.CreationDate AS LikeCreationDate, m.Id AS MessageId,
                   COALESCE(m.Content, m.ImageFile) AS MessageContent, m.CreationDate AS MessageCreationDate,
                   CASE WHEN k.Person1Id IS NULL THEN 1 ELSE 0 END AS IsNew
            FROM Message AS m
            JOIN Person_likes_Message AS l ON l.MessageId = m.Id
            JOIN Person AS f ON f.Id = l.PersonId
            LEFT JOIN Person_knows_Person AS k ON k.Person1Id = m.CreatorPersonId AND k.Person2Id = f.Id
            WHERE m.CreatorPersonId = @personId
              AND NOT EXISTS (
                  SELECT later.MessageId
                  FROM Person_likes_Message AS later
                  JOIN Message AS lm ON lm.Id = later.MessageId
                  WHERE later.PersonId = l.PersonId
                    AND lm.CreatorPersonId = @personId
                    AND (later.CreationDate > l.CreationDate
                         OR (later.CreationDate = l.CreationDate AND later.MessageId < l.MessageId)))
            ORDER BY l.CreationDate DESC, f.Id ASC
            """,
            [PersonId]),

        new("ic8", LdbcWorkload.InteractiveComplex, 8, "Recent replies", LdbcTranslation.AsSpecified,
            "The newest direct replies to the start person's messages: a self-join of Message over ParentMessageId.",
            """
            SELECT TOP (20) a.Id AS CommentAuthorId, a.FirstName AS CommentAuthorFirstName,
                   a.LastName AS CommentAuthorLastName, c.CreationDate AS CommentCreationDate,
                   c.Id AS CommentId, c.Content AS CommentContent
            FROM Message AS m
            JOIN Message AS c ON c.ParentMessageId = m.Id
            JOIN Person AS a ON a.Id = c.CreatorPersonId
            WHERE m.CreatorPersonId = @personId
            ORDER BY c.CreationDate DESC, c.Id ASC
            """,
            [PersonId]),

        new("ic9", LdbcWorkload.InteractiveComplex, 9, "Recent messages by friends or friends of friends", LdbcTranslation.AsSpecified,
            "The newest messages of persons one or two steps away, before a date.",
            """
            SELECT TOP (20) p.Id AS OtherPersonId, p.FirstName AS OtherPersonFirstName, p.LastName AS OtherPersonLastName,
                   m.Id AS MessageId, COALESCE(m.Content, m.ImageFile) AS MessageContent,
                   m.CreationDate AS MessageCreationDate
            FROM Message AS m
            JOIN Person AS p ON p.Id = m.CreatorPersonId
            WHERE m.CreationDate < @maxDate
              AND p.Id <> @personId
              AND (p.Id IN (SELECT k1.Person2Id FROM Person_knows_Person AS k1 WHERE k1.Person1Id = @personId)
                   OR p.Id IN (SELECT k2.Person2Id FROM Person_knows_Person AS k1
                               JOIN Person_knows_Person AS k2 ON k2.Person1Id = k1.Person2Id
                               WHERE k1.Person1Id = @personId))
            ORDER BY m.CreationDate DESC, m.Id ASC
            """,
            [PersonId, new("maxDate", "DATE", "2011-01-01")]),

        new("ic10", LdbcWorkload.InteractiveComplex, 10, "Friend recommendation", LdbcTranslation.AsSpecified,
            "Friends of friends who are not friends, born around a given month, ranked by the posts that do and do not carry "
            + "a tag the start person is interested in: common - uncommon is written as 2 * common - all posts. MONTH and "
            + "DAY of the birthday; the next month is the parameter @nextMonth, which the specification allows.",
            """
            SELECT TOP (10) f.Id AS PersonId, f.FirstName AS PersonFirstName, f.LastName AS PersonLastName,
                   2 * COUNT(DISTINCT CASE WHEN i.TagId IS NOT NULL THEN p.Id END) - COUNT(DISTINCT p.Id) AS CommonInterestScore,
                   f.Gender AS PersonGender, city.Name AS PersonCityName
            FROM Person AS f
            JOIN Place AS city ON city.Id = f.LocationCityId
            LEFT JOIN Message AS p ON p.CreatorPersonId = f.Id AND p.ParentMessageId IS NULL
            LEFT JOIN Message_hasTag_Tag AS pt ON pt.MessageId = p.Id
            LEFT JOIN Person_hasInterest_Tag AS i ON i.TagId = pt.TagId AND i.PersonId = @personId
            WHERE f.Id <> @personId
              AND f.Id IN (SELECT k2.Person2Id FROM Person_knows_Person AS k1
                           JOIN Person_knows_Person AS k2 ON k2.Person1Id = k1.Person2Id
                           WHERE k1.Person1Id = @personId)
              AND f.Id NOT IN (SELECT k1.Person2Id FROM Person_knows_Person AS k1 WHERE k1.Person1Id = @personId)
              AND ((MONTH(f.Birthday) = @month AND DAY(f.Birthday) >= 21)
                   OR (MONTH(f.Birthday) = @nextMonth AND DAY(f.Birthday) < 22))
            GROUP BY f.Id, f.FirstName, f.LastName, f.Gender, city.Name
            ORDER BY CommonInterestScore DESC, f.Id ASC
            """,
            [PersonId, new("month", "INT", "5"), new("nextMonth", "INT", "6")], [EFCoreJoin]),

        new("ic11", LdbcWorkload.InteractiveComplex, 11, "Job referral", LdbcTranslation.AsSpecified,
            "Friends and friends of friends who started at a company in a given country before a year; three sort keys "
            + "in two directions.",
            """
            SELECT TOP (10) p.Id AS OtherPersonId, p.FirstName AS OtherPersonFirstName, p.LastName AS OtherPersonLastName,
                   o.Name AS CompanyName, w.WorkFrom AS WorkFrom
            FROM Person AS p
            JOIN Person_workAt_Company AS w ON w.PersonId = p.Id
            JOIN Organisation AS o ON o.Id = w.CompanyId
            JOIN Place AS co ON co.Id = o.LocationPlaceId
            WHERE co.Name = @countryName
              AND w.WorkFrom < @workFromYear
              AND p.Id <> @personId
              AND (p.Id IN (SELECT k1.Person2Id FROM Person_knows_Person AS k1 WHERE k1.Person1Id = @personId)
                   OR p.Id IN (SELECT k2.Person2Id FROM Person_knows_Person AS k1
                               JOIN Person_knows_Person AS k2 ON k2.Person1Id = k1.Person2Id
                               WHERE k1.Person1Id = @personId))
            ORDER BY w.WorkFrom ASC, p.Id ASC, o.Name DESC
            """,
            [PersonId, new("countryName", "NVARCHAR(256)", "China"), new("workFromYear", "INT", "2010")]),

        new("ic12", LdbcWorkload.InteractiveComplex, 12, "Expert search", LdbcTranslation.Simplified,
            "Friends' direct replies to posts whose tag belongs to a tag class or any class below it. The class hierarchy "
            + "is static in every data set and five levels deep, so the descendants are six outer joins up the chain "
            + "instead of recursion. Left out: the names of the tags, which the specification returns as a set.",
            """
            SELECT TOP (20) f.Id AS PersonId, f.FirstName AS PersonFirstName, f.LastName AS PersonLastName,
                   COUNT(DISTINCT c.Id) AS ReplyCount
            FROM Person_knows_Person AS k
            JOIN Person AS f ON f.Id = k.Person2Id
            JOIN Message AS c ON c.CreatorPersonId = f.Id
            JOIN Message AS p ON p.Id = c.ParentMessageId
            JOIN Message_hasTag_Tag AS pt ON pt.MessageId = p.Id
            JOIN Tag AS t ON t.Id = pt.TagId
            JOIN TagClass AS tc0 ON tc0.Id = t.TypeTagClassId
            LEFT JOIN TagClass AS tc1 ON tc1.Id = tc0.SubclassOfTagClassId
            LEFT JOIN TagClass AS tc2 ON tc2.Id = tc1.SubclassOfTagClassId
            LEFT JOIN TagClass AS tc3 ON tc3.Id = tc2.SubclassOfTagClassId
            LEFT JOIN TagClass AS tc4 ON tc4.Id = tc3.SubclassOfTagClassId
            LEFT JOIN TagClass AS tc5 ON tc5.Id = tc4.SubclassOfTagClassId
            WHERE k.Person1Id = @personId
              AND p.ParentMessageId IS NULL
              AND (tc0.Name = @tagClassName OR tc1.Name = @tagClassName OR tc2.Name = @tagClassName
                   OR tc3.Name = @tagClassName OR tc4.Name = @tagClassName OR tc5.Name = @tagClassName)
            GROUP BY f.Id, f.FirstName, f.LastName
            ORDER BY ReplyCount DESC, f.Id ASC
            """,
            [PersonId, new("tagClassName", "NVARCHAR(256)", "Person")]),

        new("ic13", LdbcWorkload.InteractiveComplex, 13, "Single shortest path", LdbcTranslation.NotTranslated,
            "The length of the shortest path along knows between two persons, of any length. That is a search over the "
            + "graph - the reference implementations use a recursive common table expression or a stored procedure - "
            + "and a query of the representation is one SELECT without recursion.",
            null,
            [new("person1Id", "BIGINT", "4398046513938"), new("person2Id", "BIGINT", "65")]),

        new("ic14", LdbcWorkload.InteractiveComplex, 14, "Trusted connection paths", LdbcTranslation.NotTranslated,
            "Every shortest path between two persons, weighted by the replies between neighbours, returned as a list of "
            + "identifiers. A search over the graph and a list-valued result: neither has a place in the representation.",
            null,
            [new("person1Id", "BIGINT", "4398046513938"), new("person2Id", "BIGINT", "65")]),

        // Business Intelligence reads (specification section 8.4).

        new("bi1", LdbcWorkload.BusinessIntelligence, 1, "Posting summary", LdbcTranslation.NotTranslated,
            "Messages grouped by the year of their creation, by whether they are comments and by a length category. All "
            + "three grouping keys are expressions, and the representation groups by columns only; the share of all "
            + "messages is a scalar subquery besides.",
            """
            SELECT YEAR(m.CreationDate) AS MessageYear,
                   CASE WHEN m.ParentMessageId IS NULL THEN 0 ELSE 1 END AS IsComment,
                   CASE WHEN m.Length < 40 THEN 0 WHEN m.Length < 80 THEN 1 WHEN m.Length < 160 THEN 2 ELSE 3 END AS LengthCategory,
                   COUNT(*) AS MessageCount,
                   AVG(1.0 * m.Length) AS AverageMessageLength,
                   SUM(m.Length) AS SumMessageLength,
                   100.0 * COUNT(*) / (SELECT COUNT(*) FROM Message AS a WHERE a.CreationDate < @datetime) AS PercentageOfMessages
            FROM Message AS m
            WHERE m.CreationDate < @datetime
            GROUP BY YEAR(m.CreationDate),
                     CASE WHEN m.ParentMessageId IS NULL THEN 0 ELSE 1 END,
                     CASE WHEN m.Length < 40 THEN 0 WHEN m.Length < 80 THEN 1 WHEN m.Length < 160 THEN 2 ELSE 3 END
            ORDER BY MessageYear DESC, IsComment ASC, LengthCategory ASC
            """,
            [new("datetime", "DATETIME2(3)", "2012-06-01")]),

        new("bi2", LdbcWorkload.BusinessIntelligence, 2, "Tag evolution", LdbcTranslation.AsSpecified,
            "Messages per tag of a tag class in two consecutive 100-day windows and their absolute difference: outer "
            + "joins keep the tags with no message, counts over a CASE split the windows, ABS of a difference of "
            + "aggregates orders the result. The caller passes $date, $date + 100 days and $date + 200 days.",
            """
            SELECT TOP (100) t.Name AS TagName,
                   COUNT(CASE WHEN m.CreationDate < @window1End THEN m.Id END) AS CountWindow1,
                   COUNT(CASE WHEN m.CreationDate >= @window1End THEN m.Id END) AS CountWindow2,
                   ABS(COUNT(CASE WHEN m.CreationDate < @window1End THEN m.Id END)
                       - COUNT(CASE WHEN m.CreationDate >= @window1End THEN m.Id END)) AS Diff
            FROM TagClass AS tc
            JOIN Tag AS t ON t.TypeTagClassId = tc.Id
            LEFT JOIN Message_hasTag_Tag AS mt ON mt.TagId = t.Id
            LEFT JOIN Message AS m ON m.Id = mt.MessageId AND m.CreationDate >= @window1Start AND m.CreationDate < @window2End
            WHERE tc.Name = @tagClass
            GROUP BY t.Id, t.Name
            ORDER BY Diff DESC, t.Name ASC
            """,
            [new("tagClass", "NVARCHAR(256)", "MusicalArtist"), new("window1Start", "DATE", "2011-01-01"),
             new("window1End", "DATE", "2011-04-11"), new("window2End", "DATE", "2011-07-20")], [EFCoreJoin]),

        new("bi3", LdbcWorkload.BusinessIntelligence, 3, "Popular topics in a country", LdbcTranslation.AsSpecified,
            "Forums moderated by someone living in a country, counted by their messages with a tag of a tag class: eight "
            + "joins, two of them up the place hierarchy. A comment belongs to the forum of its thread through "
            + "ContainerForumId, so the walk along replyOf to the root post is not needed.",
            """
            SELECT TOP (20) f.Id AS ForumId, f.Title AS ForumTitle, f.CreationDate AS ForumCreationDate,
                   f.ModeratorPersonId AS PersonId, COUNT(DISTINCT m.Id) AS MessageCount
            FROM Place AS co
            JOIN Place AS ci ON ci.PartOfPlaceId = co.Id
            JOIN Person AS p ON p.LocationCityId = ci.Id
            JOIN Forum AS f ON f.ModeratorPersonId = p.Id
            JOIN Message AS m ON m.ContainerForumId = f.Id
            JOIN Message_hasTag_Tag AS mt ON mt.MessageId = m.Id
            JOIN Tag AS t ON t.Id = mt.TagId
            JOIN TagClass AS tc ON tc.Id = t.TypeTagClassId
            WHERE co.Name = @country AND tc.Name = @tagClass
            GROUP BY f.Id, f.Title, f.CreationDate, f.ModeratorPersonId
            ORDER BY MessageCount DESC, f.Id ASC
            """,
            [new("tagClass", "NVARCHAR(256)", "MusicalArtist"), new("country", "NVARCHAR(256)", "China")]),

        new("bi4", LdbcWorkload.BusinessIntelligence, 4, "Top message creators by country", LdbcTranslation.AsSpecified,
            "The 100 forums with the most members from one country, then the messages their members wrote in any of "
            + "them. The popularity of a forum is a maximum over counts - an aggregate of an aggregate - and the second "
            + "step reads the result of the first, so the text is common table expressions (decision 112): the member "
            + "counts, the top forums, and the messages written in a top forum, which the outer join of each member "
            + "reads - the same rows as an outer join filtered by IN over the top forums, which would put a subquery "
            + "into ON.",
            """
            WITH MemberCount AS (
                SELECT f.Id AS ForumId, co.Id AS CountryId, COUNT(*) AS Members
                FROM Forum AS f
                JOIN Forum_hasMember_Person AS fm ON fm.ForumId = f.Id
                JOIN Person AS p ON p.Id = fm.PersonId
                JOIN Place AS ci ON ci.Id = p.LocationCityId
                JOIN Place AS co ON co.Id = ci.PartOfPlaceId
                WHERE f.CreationDate > @date
                GROUP BY f.Id, co.Id),
            TopForum AS (
                SELECT TOP (100) mc.ForumId, MAX(mc.Members) AS Popularity
                FROM MemberCount AS mc
                GROUP BY mc.ForumId
                ORDER BY Popularity DESC, mc.ForumId ASC),
            TopForumMessage AS (
                SELECT m.Id AS MessageId, m.CreatorPersonId AS CreatorPersonId
                FROM Message AS m
                JOIN TopForum AS t2 ON t2.ForumId = m.ContainerForumId)
            SELECT TOP (100) p.Id AS PersonId, p.FirstName AS PersonFirstName, p.LastName AS PersonLastName,
                   p.CreationDate AS PersonCreationDate, COUNT(DISTINCT tm.MessageId) AS MessageCount
            FROM TopForum AS tf
            JOIN Forum_hasMember_Person AS fm ON fm.ForumId = tf.ForumId
            JOIN Person AS p ON p.Id = fm.PersonId
            LEFT JOIN TopForumMessage AS tm ON tm.CreatorPersonId = p.Id
            GROUP BY p.Id, p.FirstName, p.LastName, p.CreationDate
            ORDER BY MessageCount DESC, p.Id ASC
            """,
            [new("date", "DATE", "2010-02-01")], FallbackBy: [NHibernateIntermediate, EclipseLinkIntermediate]),

        new("bi5", LdbcWorkload.BusinessIntelligence, 5, "Most active posters of a given topic", LdbcTranslation.AsSpecified,
            "Per author of messages with a tag: the messages, the direct replies to them and the likes they received, "
            + "weighted into a score. Replies and likes both multiply the rows of a message, so the replies are counted "
            + "as distinct identifiers and the likes by a correlated scalar subquery in the projection.",
            """
            SELECT TOP (100) m.CreatorPersonId AS PersonId,
                   COUNT(DISTINCT r.Id) AS ReplyCount,
                   (SELECT COUNT(*) FROM Person_likes_Message AS l
                    JOIN Message_hasTag_Tag AS lt ON lt.MessageId = l.MessageId
                    JOIN Message AS lm ON lm.Id = l.MessageId
                    WHERE lm.CreatorPersonId = m.CreatorPersonId AND lt.TagId = t.Id) AS LikeCount,
                   COUNT(DISTINCT m.Id) AS MessageCount,
                   COUNT(DISTINCT m.Id) + 2 * COUNT(DISTINCT r.Id)
                   + 10 * (SELECT COUNT(*) FROM Person_likes_Message AS l
                           JOIN Message_hasTag_Tag AS lt ON lt.MessageId = l.MessageId
                           JOIN Message AS lm ON lm.Id = l.MessageId
                           WHERE lm.CreatorPersonId = m.CreatorPersonId AND lt.TagId = t.Id) AS Score
            FROM Tag AS t
            JOIN Message_hasTag_Tag AS mt ON mt.TagId = t.Id
            JOIN Message AS m ON m.Id = mt.MessageId
            LEFT JOIN Message AS r ON r.ParentMessageId = m.Id
            WHERE t.Name = @tag
            GROUP BY m.CreatorPersonId, t.Id
            ORDER BY Score DESC, m.CreatorPersonId ASC
            """,
            [new("tag", "NVARCHAR(256)", "Hamid_Karzai")]),

        new("bi6", LdbcWorkload.BusinessIntelligence, 6, "Most authoritative users on a given topic", LdbcTranslation.AsSpecified,
            "The authority of an author of messages with a tag is the sum of the popularity of everyone who liked those "
            + "messages. Every like of a liker's message counts once, so the sum is a count of likes on messages whose "
            + "author is in the set of likers - a scalar subquery with an IN subquery inside it.",
            """
            SELECT TOP (100) m.CreatorPersonId AS Person1Id,
                   (SELECT COUNT(*) FROM Person_likes_Message AS l3
                    JOIN Message AS m2 ON m2.Id = l3.MessageId
                    WHERE m2.CreatorPersonId IN (
                        SELECT l2.PersonId FROM Person_likes_Message AS l2
                        JOIN Message AS m1 ON m1.Id = l2.MessageId
                        JOIN Message_hasTag_Tag AS mt1 ON mt1.MessageId = m1.Id
                        WHERE m1.CreatorPersonId = m.CreatorPersonId AND mt1.TagId = t.Id)) AS AuthorityScore
            FROM Tag AS t
            JOIN Message_hasTag_Tag AS mt ON mt.TagId = t.Id
            JOIN Message AS m ON m.Id = mt.MessageId
            WHERE t.Name = @tag
            GROUP BY m.CreatorPersonId, t.Id
            ORDER BY AuthorityScore DESC, m.CreatorPersonId ASC
            """,
            [new("tag", "NVARCHAR(256)", "Peter_Hain")]),

        new("bi7", LdbcWorkload.BusinessIntelligence, 7, "Related topics", LdbcTranslation.AsSpecified,
            "The tags of direct replies to messages with a tag, among the replies that do not carry that tag themselves: "
            + "a negative edge as NOT EXISTS, grouped by name.",
            """
            SELECT TOP (100) rt.Name AS RelatedTagName, COUNT(DISTINCT c.Id) AS ReplyCount
            FROM Tag AS t
            JOIN Message_hasTag_Tag AS mt ON mt.TagId = t.Id
            JOIN Message AS c ON c.ParentMessageId = mt.MessageId
            JOIN Message_hasTag_Tag AS ct ON ct.MessageId = c.Id
            JOIN Tag AS rt ON rt.Id = ct.TagId
            WHERE t.Name = @tag
              AND NOT EXISTS (
                  SELECT own.TagId FROM Message_hasTag_Tag AS own
                  WHERE own.MessageId = c.Id AND own.TagId = t.Id)
            GROUP BY rt.Name
            ORDER BY ReplyCount DESC, rt.Name ASC
            """,
            [new("tag", "NVARCHAR(256)", "Genghis_Khan")]),

        new("bi8", LdbcWorkload.BusinessIntelligence, 8, "Central person for a tag", LdbcTranslation.AsSpecified,
            "Persons interested in a tag or writing messages with it inside an open interval, scored 100 for the interest "
            + "plus one per message, and beside it the friends' score, the sum of the scores of each person's friends. "
            + "The friends' score reads the scores themselves, so they are a common table expression the query reads "
            + "twice (decision 112): once for the person and once, over knows, for the friends.",
            """
            WITH PersonScore AS (
                SELECT p.Id AS PersonId,
                       CASE WHEN i.PersonId IS NULL THEN 0 ELSE 100 END + COUNT(DISTINCT mt.MessageId) AS Score
                FROM Person AS p
                JOIN Tag AS t ON t.Name = @tag
                LEFT JOIN Person_hasInterest_Tag AS i ON i.PersonId = p.Id AND i.TagId = t.Id
                LEFT JOIN Message AS m ON m.CreatorPersonId = p.Id AND m.CreationDate > @startDate AND m.CreationDate < @endDate
                LEFT JOIN Message_hasTag_Tag AS mt ON mt.MessageId = m.Id AND mt.TagId = t.Id
                WHERE i.PersonId IS NOT NULL OR mt.MessageId IS NOT NULL
                GROUP BY p.Id, i.PersonId)
            SELECT TOP (100) ps.PersonId AS PersonId, ps.Score AS Score, COALESCE(SUM(fs.Score), 0) AS FriendsScore
            FROM PersonScore AS ps
            LEFT JOIN Person_knows_Person AS k ON k.Person1Id = ps.PersonId
            LEFT JOIN PersonScore AS fs ON fs.PersonId = k.Person2Id
            GROUP BY ps.PersonId, ps.Score
            ORDER BY ps.Score + COALESCE(SUM(fs.Score), 0) DESC, ps.PersonId ASC
            """,
            [new("tag", "NVARCHAR(256)", "Sammy_Sosa"), new("startDate", "DATE", "2011-01-01"), new("endDate", "DATE", "2011-06-01")],
            [EFCoreJoin], [NHibernateIntermediate, EclipseLinkIntermediate]),

        new("bi9", LdbcWorkload.BusinessIntelligence, 9, "Top thread initiators", LdbcTranslation.AsSpecified,
            "Per person, the threads started in an interval and all their messages in it, root included. The whole "
            + "reply tree of a post is the set of messages with that RootPostId, so the transitive walk is one join.",
            """
            SELECT TOP (100) p.Id AS PersonId, p.FirstName AS PersonFirstName, p.LastName AS PersonLastName,
                   COUNT(DISTINCT r.Id) AS ThreadCount, COUNT(DISTINCT m.Id) AS MessageCount
            FROM Person AS p
            JOIN Message AS r ON r.CreatorPersonId = p.Id
            JOIN Message AS m ON m.RootPostId = r.Id
            WHERE r.ParentMessageId IS NULL
              AND r.CreationDate >= @startDate AND r.CreationDate <= @endDate
              AND m.CreationDate >= @startDate AND m.CreationDate <= @endDate
            GROUP BY p.Id, p.FirstName, p.LastName
            ORDER BY MessageCount DESC, p.Id ASC
            """,
            [new("startDate", "DATE", "2011-01-01"), new("endDate", "DATE", "2011-03-31")]),

        new("bi10", LdbcWorkload.BusinessIntelligence, 10, "Experts in social circle", LdbcTranslation.AsSpecified,
            "Persons whose shortest distance from the start person is 3 or 4 - the bounds the specification fixes - "
            + "living in a country, and their messages with a tag of a tag class, counted per tag. The distance is "
            + "stated without recursion as reachable in three or four steps and not in one or two.",
            """
            SELECT TOP (100) e.Id AS ExpertCandidatePersonId, t.Name AS TagName, COUNT(DISTINCT m.Id) AS MessageCount
            FROM Person AS e
            JOIN Place AS ci ON ci.Id = e.LocationCityId
            JOIN Place AS co ON co.Id = ci.PartOfPlaceId
            JOIN Message AS m ON m.CreatorPersonId = e.Id
            JOIN Message_hasTag_Tag AS mt ON mt.MessageId = m.Id
            JOIN Tag AS t ON t.Id = mt.TagId
            WHERE co.Name = @country
              AND e.Id <> @personId
              AND (e.Id IN (SELECT k3.Person2Id FROM Person_knows_Person AS k1
                            JOIN Person_knows_Person AS k2 ON k2.Person1Id = k1.Person2Id
                            JOIN Person_knows_Person AS k3 ON k3.Person1Id = k2.Person2Id
                            WHERE k1.Person1Id = @personId)
                   OR e.Id IN (SELECT k4.Person2Id FROM Person_knows_Person AS k1
                               JOIN Person_knows_Person AS k2 ON k2.Person1Id = k1.Person2Id
                               JOIN Person_knows_Person AS k3 ON k3.Person1Id = k2.Person2Id
                               JOIN Person_knows_Person AS k4 ON k4.Person1Id = k3.Person2Id
                               WHERE k1.Person1Id = @personId))
              AND e.Id NOT IN (SELECT k1.Person2Id FROM Person_knows_Person AS k1 WHERE k1.Person1Id = @personId)
              AND e.Id NOT IN (SELECT k2.Person2Id FROM Person_knows_Person AS k1
                               JOIN Person_knows_Person AS k2 ON k2.Person1Id = k1.Person2Id
                               WHERE k1.Person1Id = @personId)
              AND EXISTS (
                  SELECT ct.TagId FROM Message_hasTag_Tag AS ct
                  JOIN Tag AS ctt ON ctt.Id = ct.TagId
                  JOIN TagClass AS tc ON tc.Id = ctt.TypeTagClassId
                  WHERE ct.MessageId = m.Id AND tc.Name = @tagClass)
            GROUP BY e.Id, t.Name
            ORDER BY MessageCount DESC, t.Name ASC, e.Id ASC
            """,
            [PersonId, new("country", "NVARCHAR(256)", "China"), new("tagClass", "NVARCHAR(256)", "MusicalArtist")]),

        new("bi11", LdbcWorkload.BusinessIntelligence, 11, "Friend triangles", LdbcTranslation.AsSpecified,
            "Triangles of friendships created in an interval among persons of one country: a cyclic self-join of the edge "
            + "table, counted once per triangle by ordering the three identifiers.",
            """
            SELECT COUNT(*) AS TriangleCount
            FROM Person_knows_Person AS kab
            JOIN Person_knows_Person AS kbc ON kbc.Person1Id = kab.Person2Id
            JOIN Person_knows_Person AS kca ON kca.Person1Id = kbc.Person2Id AND kca.Person2Id = kab.Person1Id
            JOIN Person AS a ON a.Id = kab.Person1Id
            JOIN Person AS b ON b.Id = kbc.Person1Id
            JOIN Person AS c ON c.Id = kca.Person1Id
            JOIN Place AS ca ON ca.Id = a.LocationCityId
            JOIN Place AS cb ON cb.Id = b.LocationCityId
            JOIN Place AS cc ON cc.Id = c.LocationCityId
            JOIN Place AS co ON co.Id = ca.PartOfPlaceId
            WHERE co.Name = @country
              AND cb.PartOfPlaceId = co.Id AND cc.PartOfPlaceId = co.Id
              AND a.Id < b.Id AND b.Id < c.Id
              AND kab.CreationDate >= @startDate AND kab.CreationDate <= @endDate
              AND kbc.CreationDate >= @startDate AND kbc.CreationDate <= @endDate
              AND kca.CreationDate >= @startDate AND kca.CreationDate <= @endDate
            """,
            [new("country", "NVARCHAR(256)", "India"), new("startDate", "DATE", "2010-06-01"), new("endDate", "DATE", "2011-06-01")], FallbackBy: [EFCoreCount]),

        new("bi12", LdbcWorkload.BusinessIntelligence, 12, "How many persons have a given number of messages", LdbcTranslation.AsSpecified,
            "A histogram: messages per person, then persons per number of messages. The second grouping is over the "
            + "result of the first - a derived table in FROM, which the representation carries as an intermediate result "
            + "of the query (decision 112).",
            """
            SELECT pc.MessageCount, COUNT(*) AS PersonCount
            FROM (SELECT p.Id AS PersonId, COUNT(m.Id) AS MessageCount
                  FROM Person AS p
                  LEFT JOIN Message AS m ON m.CreatorPersonId = p.Id
                       AND m.Content IS NOT NULL
                       AND m.Length < @lengthThreshold
                       AND m.CreationDate > @startDate
                       AND m.RootPostLanguage IN @languages
                  GROUP BY p.Id) AS pc
            GROUP BY pc.MessageCount
            ORDER BY PersonCount DESC, pc.MessageCount DESC
            """,
            [new("startDate", "DATE", "2011-06-01"), new("lengthThreshold", "INT", "100"),
             new("languages", "VARCHAR(40)", "ar,hu", IsList: true)], [EFCoreJoin, EclipseLinkNativeList], [NHibernateIntermediate]),

        new("bi13", LdbcWorkload.BusinessIntelligence, 13, "Zombies in a country", LdbcTranslation.AsSpecified,
            "Zombies are persons of a country who wrote on average less than one message a month; the months are counted "
            + "with YEAR and MONTH and compared in HAVING. The likes a zombie received are counted twice - from every "
            + "liker created before the end date and from the zombies among them - and their ratio is the score. Telling "
            + "a zombie liker needs the zombies as rows to join, so they are a common table expression the query reads "
            + "twice (decision 112), and the counts a second one, which the score divides.",
            """
            WITH Zombie AS (
                SELECT zp.Id AS ZombieId
                FROM Person AS zp
                JOIN Place AS zci ON zci.Id = zp.LocationCityId
                JOIN Place AS zco ON zco.Id = zci.PartOfPlaceId
                LEFT JOIN Message AS zm ON zm.CreatorPersonId = zp.Id AND zm.CreationDate < @endDate
                WHERE zco.Name = @country AND zp.CreationDate < @endDate
                GROUP BY zp.Id, zp.CreationDate
                HAVING COUNT(zm.Id) < (YEAR(@endDate) - YEAR(zp.CreationDate)) * 12 + MONTH(@endDate) - MONTH(zp.CreationDate) + 1),
            ZombieLikes AS (
                SELECT z.ZombieId AS ZombieId, COUNT(liker.Id) AS TotalLikeCount, COUNT(lz.ZombieId) AS ZombieLikeCount
                FROM Zombie AS z
                LEFT JOIN Message AS m ON m.CreatorPersonId = z.ZombieId
                LEFT JOIN Person_likes_Message AS l ON l.MessageId = m.Id
                LEFT JOIN Person AS liker ON liker.Id = l.PersonId AND liker.CreationDate < @endDate
                LEFT JOIN Zombie AS lz ON lz.ZombieId = liker.Id
                GROUP BY z.ZombieId)
            SELECT TOP (100) zl.ZombieId AS ZombieId, zl.ZombieLikeCount AS ZombieLikeCount, zl.TotalLikeCount AS TotalLikeCount,
                   CASE WHEN zl.TotalLikeCount = 0 THEN 0.0 ELSE 1.0 * zl.ZombieLikeCount / zl.TotalLikeCount END AS ZombieScore
            FROM ZombieLikes AS zl
            ORDER BY ZombieScore DESC, zl.ZombieId ASC
            """,
            [new("country", "NVARCHAR(256)", "India"), new("endDate", "DATE", "2012-09-01")],
            [EFCoreJoin], [NHibernateIntermediate, EclipseLinkIntermediate]),

        new("bi14", LdbcWorkload.BusinessIntelligence, 14, "International dialog", LdbcTranslation.Simplified,
            "Pairs of friends from two countries scored by four kinds of interaction, each a CASE over EXISTS. Left out: "
            + "keeping only the best pair of every city, which ranks rows within a group - a window function the "
            + "representation does not carry; the text returns the best pairs overall.",
            """
            SELECT TOP (100) p1.Id AS Person1Id, p2.Id AS Person2Id, ci1.Name AS City1Name,
                   CASE WHEN EXISTS (SELECT c.Id FROM Message AS c JOIN Message AS pm ON pm.Id = c.ParentMessageId
                                     WHERE c.CreatorPersonId = p1.Id AND pm.CreatorPersonId = p2.Id) THEN 4 ELSE 0 END
                 + CASE WHEN EXISTS (SELECT c.Id FROM Message AS c JOIN Message AS pm ON pm.Id = c.ParentMessageId
                                     WHERE c.CreatorPersonId = p2.Id AND pm.CreatorPersonId = p1.Id) THEN 1 ELSE 0 END
                 + CASE WHEN EXISTS (SELECT l.MessageId FROM Person_likes_Message AS l JOIN Message AS lm ON lm.Id = l.MessageId
                                     WHERE l.PersonId = p1.Id AND lm.CreatorPersonId = p2.Id) THEN 10 ELSE 0 END
                 + CASE WHEN EXISTS (SELECT l.MessageId FROM Person_likes_Message AS l JOIN Message AS lm ON lm.Id = l.MessageId
                                     WHERE l.PersonId = p2.Id AND lm.CreatorPersonId = p1.Id) THEN 1 ELSE 0 END AS Score
            FROM Person AS p1
            JOIN Place AS ci1 ON ci1.Id = p1.LocationCityId
            JOIN Place AS co1 ON co1.Id = ci1.PartOfPlaceId
            JOIN Person_knows_Person AS k ON k.Person1Id = p1.Id
            JOIN Person AS p2 ON p2.Id = k.Person2Id
            JOIN Place AS ci2 ON ci2.Id = p2.LocationCityId
            JOIN Place AS co2 ON co2.Id = ci2.PartOfPlaceId
            WHERE co1.Name = @country1 AND co2.Name = @country2
            ORDER BY Score DESC, p1.Id ASC, p2.Id ASC
            """,
            [new("country1", "NVARCHAR(256)", "India"), new("country2", "NVARCHAR(256)", "China")]),

        new("bi15", LdbcWorkload.BusinessIntelligence, 15, "Trusted connection paths through forums created in a given timeframe", LdbcTranslation.NotTranslated,
            "The cost of the weighted shortest path between two persons, the weight of an edge coming from the replies "
            + "between its ends. A weighted search over the graph, which no single SELECT without recursion states.",
            null,
            [new("person1Id", "BIGINT", "4398046513938"), new("person2Id", "BIGINT", "65"),
             new("startDate", "DATE", "2011-01-01"), new("endDate", "DATE", "2011-02-01")]),

        new("bi16", LdbcWorkload.BusinessIntelligence, 16, "Fake news detection", LdbcTranslation.AsSpecified,
            "Persons who wrote about two tags on two given days, keeping those with few friends who did the same: the "
            + "friend count is a correlated scalar subquery compared with @maxKnowsLimit, which takes its type from "
            + "the count, the two message counts are counts over a CASE, and the order is the sum of two aggregates. "
            + "The caller passes the day after $dateA and the day after $dateB as @dateAEnd and @dateBEnd.",
            """
            SELECT TOP (20) p.Id AS PersonId,
                   COUNT(DISTINCT CASE WHEN t.Name = @tagA AND m.CreationDate >= @dateA AND m.CreationDate < @dateAEnd THEN m.Id END) AS MessageCountA,
                   COUNT(DISTINCT CASE WHEN t.Name = @tagB AND m.CreationDate >= @dateB AND m.CreationDate < @dateBEnd THEN m.Id END) AS MessageCountB
            FROM Person AS p
            JOIN Message AS m ON m.CreatorPersonId = p.Id
            JOIN Message_hasTag_Tag AS mt ON mt.MessageId = m.Id
            JOIN Tag AS t ON t.Id = mt.TagId
            WHERE ((t.Name = @tagA AND m.CreationDate >= @dateA AND m.CreationDate < @dateAEnd)
                   OR (t.Name = @tagB AND m.CreationDate >= @dateB AND m.CreationDate < @dateBEnd))
              AND (SELECT COUNT(DISTINCT k.Person2Id) FROM Person_knows_Person AS k
                   JOIN Message AS fm ON fm.CreatorPersonId = k.Person2Id
                   JOIN Message_hasTag_Tag AS fmt ON fmt.MessageId = fm.Id
                   JOIN Tag AS ft ON ft.Id = fmt.TagId
                   WHERE k.Person1Id = p.Id AND ft.Name = @tagA
                     AND fm.CreationDate >= @dateA AND fm.CreationDate < @dateAEnd) <= @maxKnowsLimit
              AND (SELECT COUNT(DISTINCT k.Person2Id) FROM Person_knows_Person AS k
                   JOIN Message AS fm ON fm.CreatorPersonId = k.Person2Id
                   JOIN Message_hasTag_Tag AS fmt ON fmt.MessageId = fm.Id
                   JOIN Tag AS ft ON ft.Id = fmt.TagId
                   WHERE k.Person1Id = p.Id AND ft.Name = @tagB
                     AND fm.CreationDate >= @dateB AND fm.CreationDate < @dateBEnd) <= @maxKnowsLimit
            GROUP BY p.Id
            HAVING COUNT(DISTINCT CASE WHEN t.Name = @tagA AND m.CreationDate >= @dateA AND m.CreationDate < @dateAEnd THEN m.Id END) > 0
               AND COUNT(DISTINCT CASE WHEN t.Name = @tagB AND m.CreationDate >= @dateB AND m.CreationDate < @dateBEnd THEN m.Id END) > 0
            ORDER BY COUNT(DISTINCT CASE WHEN t.Name = @tagA AND m.CreationDate >= @dateA AND m.CreationDate < @dateAEnd THEN m.Id END)
                     + COUNT(DISTINCT CASE WHEN t.Name = @tagB AND m.CreationDate >= @dateB AND m.CreationDate < @dateBEnd THEN m.Id END) DESC,
                     p.Id ASC
            """,
            [new("tagA", "NVARCHAR(256)", "Imelda_Marcos"), new("dateA", "DATE", "2012-05-08"), new("dateAEnd", "DATE", "2012-05-09"),
             new("tagB", "NVARCHAR(256)", "Muammar_Gaddafi"), new("dateB", "DATE", "2011-10-16"), new("dateBEnd", "DATE", "2011-10-17"),
             new("maxKnowsLimit", "INT", "5")]),

        new("bi17", LdbcWorkload.BusinessIntelligence, 17, "Information propagation analysis", LdbcTranslation.Simplified,
            "A message with a tag in one forum, a later message with the tag by a member of that forum in another forum "
            + "the first author is not a member of, and a tagged reply to it by a third member: a cyclic pattern of "
            + "eight joins with a NOT EXISTS. Left out: the delay of $delta hours between the two messages, which is "
            + "date arithmetic; the text only requires the second message to be later.",
            """
            SELECT TOP (10) m1.CreatorPersonId AS Person1Id, COUNT(DISTINCT m2.Id) AS MessageCount
            FROM Tag AS t
            JOIN Message_hasTag_Tag AS mt1 ON mt1.TagId = t.Id
            JOIN Message AS m1 ON m1.Id = mt1.MessageId
            JOIN Message_hasTag_Tag AS mt2 ON mt2.TagId = t.Id
            JOIN Message AS m2 ON m2.Id = mt2.MessageId
            JOIN Message AS c ON c.ParentMessageId = m2.Id
            JOIN Message_hasTag_Tag AS ct ON ct.MessageId = c.Id AND ct.TagId = t.Id
            JOIN Forum_hasMember_Person AS fm2 ON fm2.ForumId = m1.ContainerForumId AND fm2.PersonId = m2.CreatorPersonId
            JOIN Forum_hasMember_Person AS fm3 ON fm3.ForumId = m1.ContainerForumId AND fm3.PersonId = c.CreatorPersonId
            WHERE t.Name = @tag
              AND m2.CreatorPersonId <> c.CreatorPersonId
              AND m2.ContainerForumId <> m1.ContainerForumId
              AND m2.CreationDate > m1.CreationDate
              AND NOT EXISTS (
                  SELECT fm1.PersonId FROM Forum_hasMember_Person AS fm1
                  WHERE fm1.ForumId = m2.ContainerForumId AND fm1.PersonId = m1.CreatorPersonId)
            GROUP BY m1.CreatorPersonId
            ORDER BY MessageCount DESC, m1.CreatorPersonId ASC
            """,
            [new("tag", "NVARCHAR(256)", "A_Whiter_Shade_of_Pale")]),

        new("bi18", LdbcWorkload.BusinessIntelligence, 18, "Friend recommendation", LdbcTranslation.AsSpecified,
            "Pairs of persons interested in a tag who are not friends yet, ranked by their mutual friends: two steps along "
            + "knows, a negative edge as NOT EXISTS, and a distinct count of the person in the middle.",
            """
            SELECT TOP (20) k1.Person1Id AS Person1Id, k2.Person2Id AS Person2Id, COUNT(DISTINCT k1.Person2Id) AS MutualFriendCount
            FROM Tag AS t
            JOIN Person_hasInterest_Tag AS i1 ON i1.TagId = t.Id
            JOIN Person_knows_Person AS k1 ON k1.Person1Id = i1.PersonId
            JOIN Person_knows_Person AS k2 ON k2.Person1Id = k1.Person2Id
            JOIN Person_hasInterest_Tag AS i2 ON i2.PersonId = k2.Person2Id AND i2.TagId = t.Id
            WHERE t.Name = @tag
              AND k2.Person2Id <> k1.Person1Id
              AND NOT EXISTS (
                  SELECT k3.Person2Id FROM Person_knows_Person AS k3
                  WHERE k3.Person1Id = k1.Person1Id AND k3.Person2Id = k2.Person2Id)
            GROUP BY k1.Person1Id, k2.Person2Id
            ORDER BY MutualFriendCount DESC, k1.Person1Id ASC, k2.Person2Id ASC
            """,
            [new("tag", "NVARCHAR(256)", "Augustine_of_Hippo")]),

        new("bi19", LdbcWorkload.BusinessIntelligence, 19, "Interaction path between cities", LdbcTranslation.NotTranslated,
            "The cheapest paths between persons of two cities, an edge weighing max(round(40 - sqrt(interactions)), 1). "
            + "A weighted search over the graph, and ROUND and SQRT are outside the vocabulary of expressions besides.",
            null,
            [new("city1Id", "BIGINT", "1226"), new("city2Id", "BIGINT", "1353")]),

        new("bi20", LdbcWorkload.BusinessIntelligence, 20, "Recruitment", LdbcTranslation.NotTranslated,
            "The cheapest path from employees of a company to a person, through friends who studied at the same "
            + "university, an edge weighing the difference of their class years. A weighted search over the graph.",
            null,
            [new("company", "NVARCHAR(256)", "MDLR_Airlines"), new("person2Id", "BIGINT", "4398046513938")]),
    ];
}
