<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AbstractWrappers\AbstractWrappers.csproj" />
    <ProjectReference Include="..\JakartaPersistence\JakartaPersistence.csproj" />
    <ProjectReference Include="..\JavaEntityParsing\JavaEntityParsing.csproj" />
    <ProjectReference Include="..\Model\Model.csproj" />
  </ItemGroup>

</Project>
