using EFCoreWrappers;
using Model;
using Model.AbstractRepresentation.Enums;

namespace Tests.EFCore;

/// <summary>
/// EF Core states how a key value arises in two places: the [DatabaseGenerated] annotation and,
/// far more often, a convention that depends on the type of the key. Reading only the first one
/// makes every key look generated; reading neither makes none of them look generated.
/// </summary>
public class EFCoreKeyStrategyTest
{
    private static string Entity(string keyProperty) => $$"""
        public class Customer
        {
        {{keyProperty}}

            public string Name { get; set; }
        }
        """;

    private static EFCoreEntityBuilder Parse(string source)
    {
        var builder = new EFCoreEntityBuilder();
        new EFCoreEntityParser(builder).Parse(source);
        return builder;
    }

    // Guid is missing on purpose: the type model has no value for it, so CLRTypeConvertor throws
    // on the property long before the key is built. The parser maps Guid to Uuid all the same,
    // and the case becomes testable once the type model carries the type.
    [Theory]
    [InlineData("    [Key]\n    public int CustomerID { get; set; }", PrimaryKeyStrategy.Auto)]
    [InlineData("    [Key]\n    public long CustomerID { get; set; }", PrimaryKeyStrategy.Auto)]
    [InlineData("    [Key]\n    public byte CustomerID { get; set; }", PrimaryKeyStrategy.Auto)]
    [InlineData("    [Key]\n    public string CustomerID { get; set; }", PrimaryKeyStrategy.Assigned)]
    public void StrategyOfAnUnannotatedKeyFollowsItsType(string keyProperty, PrimaryKeyStrategy expected)
    {
        var builder = Parse(Entity(keyProperty.Replace("\n", "\r\n")));

        // Treating every [Key] as an identity column is what produced <generator class="identity" />
        // for a string key - a mapping the database rejects.
        Assert.Equal(expected, Assert.Single(builder.EntityMap.PrimaryKey!.Parts).Strategy);
    }

    [Fact]
    public void AnnotationOverridesTheConventionAndSurvivesGeneration()
    {
        var builder = Parse(Entity("""
                [Key]
                [DatabaseGenerated(DatabaseGeneratedOption.None)]
                public int CustomerID { get; set; }
        """));

        Assert.Equal(PrimaryKeyStrategy.Assigned, Assert.Single(builder.EntityMap.PrimaryKey!.Parts).Strategy);

        // Here the annotation has to be written back: without it EF Core would generate the
        // value for an int key by convention, so silence would reverse the claim.
        var code = builder.Build().Single().Content;
        Assert.Contains("[DatabaseGenerated(DatabaseGeneratedOption.None)]", code);
    }

    [Fact]
    public void ConventionalGenerationIsNotRestatedInTheOutput()
    {
        var builder = Parse(Entity("""
                [Key]
                public int CustomerID { get; set; }
        """));

        // Auto on an int key is exactly what EF Core does on its own, so the artifact stays as
        // it was; the annotation appears only where it changes something.
        var code = builder.Build().Single().Content;
        Assert.DoesNotContain("[DatabaseGenerated", code);
    }

    [Fact]
    public void GeneratedKeyOfATypeEFCoreDoesNotGenerateIsMadeExplicit()
    {
        var builder = new EFCoreEntityBuilder();
        builder.AddClassHeader("public", "Customer");
        builder.AddTable("Customers");
        builder.AddProperty("string", "CustomerCode", "public", hasGetter: true, hasSetter: true);
        builder.AddPrimaryKey(PrimaryKeyStrategy.Auto, "CustomerCode");

        // A string key is not generated by convention, so the claim has to be written down -
        // this is the direction that arrives from NHibernate's native generator.
        var code = builder.Build().Single().Content;
        Assert.Contains("[DatabaseGenerated(DatabaseGeneratedOption.Identity)]", code);
    }
}