-- Schema owned by the test suite (decision 016). It is created before the database
-- collection runs and dropped afterwards; nothing here refers to WideWorldImporters.
--
-- The fixture is at the same time the expected answer: with Dapper as the source only
-- property names and language types arrive, so table names, column names, types, keys
-- and foreign keys must come out of this schema. What it therefore has to contain is
-- exactly the cases F1-F4 talk about - composite keys of two, three and four parts,
-- multi-column foreign keys and a junction table - plus enough type variety for the
-- share of correctly retrieved metadata to mean something.
--
-- The {{schema}} placeholder is substituted by TestSchemaFixture. Batches are separated
-- by a line containing only GO, because CREATE SCHEMA must start its own batch.

CREATE SCHEMA [{{schema}}];
GO

-- Single-part key, generated by the database (IDENTITY).
CREATE TABLE [{{schema}}].[Customers] (
    [CustomerId]   INT             IDENTITY(1,1) NOT NULL,
    [Name]         NVARCHAR(100)   NOT NULL,
    [Notes]        NVARCHAR(400)   NULL,
    CONSTRAINT [PK_Customers] PRIMARY KEY ([CustomerId])
);
GO

-- One-to-one over a shared primary key: the key is at the same time the foreign key.
CREATE TABLE [{{schema}}].[CustomerProfiles] (
    [CustomerId]   INT             NOT NULL,
    [Website]      NVARCHAR(200)   NULL,
    [CreditLimit]  DECIMAL(18,2)   NULL,
    CONSTRAINT [PK_CustomerProfiles] PRIMARY KEY ([CustomerId]),
    CONSTRAINT [FK_CustomerProfiles_Customers] FOREIGN KEY ([CustomerId])
        REFERENCES [{{schema}}].[Customers] ([CustomerId])
);
GO

-- Two-part composite key, plus a single-column foreign key to a single-part key.
CREATE TABLE [{{schema}}].[Orders] (
    [CompanyId]    INT             NOT NULL,
    [OrderId]      INT             NOT NULL,
    [CustomerId]   INT             NOT NULL,
    [OrderDate]    DATE            NOT NULL,
    [PlacedAt]     DATETIME2(3)    NOT NULL,
    [IsCancelled]  BIT             NOT NULL,
    [ExternalRef]  UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_Orders] PRIMARY KEY ([CompanyId], [OrderId]),
    CONSTRAINT [FK_Orders_Customers] FOREIGN KEY ([CustomerId])
        REFERENCES [{{schema}}].[Customers] ([CustomerId])
);
GO

-- Three-part composite key whose leading two parts are a multi-column foreign key.
CREATE TABLE [{{schema}}].[OrderLines] (
    [CompanyId]    INT             NOT NULL,
    [OrderId]      INT             NOT NULL,
    [LineNo]       INT             NOT NULL,
    [ProductId]    INT             NOT NULL,
    [Description]  NVARCHAR(200)   NOT NULL,
    [Quantity]     INT             NOT NULL,
    [UnitPrice]    DECIMAL(18,4)   NOT NULL,
    CONSTRAINT [PK_OrderLines] PRIMARY KEY ([CompanyId], [OrderId], [LineNo]),
    CONSTRAINT [FK_OrderLines_Orders] FOREIGN KEY ([CompanyId], [OrderId])
        REFERENCES [{{schema}}].[Orders] ([CompanyId], [OrderId])
);
GO

-- Four-part composite key with a three-column foreign key.
CREATE TABLE [{{schema}}].[OrderLineAllocations] (
    [CompanyId]        INT           NOT NULL,
    [OrderId]          INT           NOT NULL,
    [LineNo]           INT           NOT NULL,
    [AllocationId]     INT           NOT NULL,
    [AllocatedQuantity] INT          NOT NULL,
    [Notes]            NVARCHAR(400) NULL,
    CONSTRAINT [PK_OrderLineAllocations] PRIMARY KEY ([CompanyId], [OrderId], [LineNo], [AllocationId]),
    CONSTRAINT [FK_OrderLineAllocations_OrderLines] FOREIGN KEY ([CompanyId], [OrderId], [LineNo])
        REFERENCES [{{schema}}].[OrderLines] ([CompanyId], [OrderId], [LineNo])
);
GO

-- Single-part key assigned by the application (no IDENTITY), and the widest type variety.
CREATE TABLE [{{schema}}].[Products] (
    [ProductId]       INT             NOT NULL,
    [ProductName]     NVARCHAR(100)   NOT NULL,
    [Sku]             VARCHAR(32)     NOT NULL,
    [UnitPrice]       DECIMAL(18,4)   NOT NULL,
    [Weight]          FLOAT           NULL,
    [IsDiscontinued]  BIT             NOT NULL,
    [IntroducedOn]    DATE            NULL,
    [LastModified]    DATETIME2(3)    NOT NULL,
    [Description]     NVARCHAR(MAX)   NULL,
    CONSTRAINT [PK_Products] PRIMARY KEY ([ProductId]),
    CONSTRAINT [UQ_Products_Sku] UNIQUE ([Sku])
);
GO

CREATE TABLE [{{schema}}].[Suppliers] (
    [SupplierId]   INT             IDENTITY(1,1) NOT NULL,
    [SupplierName] NVARCHAR(100)   NOT NULL,
    CONSTRAINT [PK_Suppliers] PRIMARY KEY ([SupplierId])
);
GO

-- Junction table: its whole primary key consists of two foreign keys and it carries
-- one payload column, so it is the many-to-many case of decision 005.
CREATE TABLE [{{schema}}].[ProductSuppliers] (
    [ProductId]    INT             NOT NULL,
    [SupplierId]   INT             NOT NULL,
    [SupplierSku]  VARCHAR(32)     NULL,
    CONSTRAINT [PK_ProductSuppliers] PRIMARY KEY ([ProductId], [SupplierId]),
    CONSTRAINT [FK_ProductSuppliers_Products] FOREIGN KEY ([ProductId])
        REFERENCES [{{schema}}].[Products] ([ProductId]),
    CONSTRAINT [FK_ProductSuppliers_Suppliers] FOREIGN KEY ([SupplierId])
        REFERENCES [{{schema}}].[Suppliers] ([SupplierId])
);
GO

-- The order line points at a product as well, which makes OrderLines a table with two
-- foreign keys of different width.
ALTER TABLE [{{schema}}].[OrderLines]
    ADD CONSTRAINT [FK_OrderLines_Products] FOREIGN KEY ([ProductId])
        REFERENCES [{{schema}}].[Products] ([ProductId]);
GO
